/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export enum VoteStatus {
    pending = 'pending',
    open = 'open',
    closed = 'closed',
}

export type CreateVote = {
    name: string;
};

export type CreateVoteOption = {
    name: string;
};

export type DiscordUser = {
    id: string;
    username: string;
    is_owner: boolean;
};

/**
 * A generic error response.
 */
export type ErrorResponse = {
    /**
     * A description of the error.
     */
    detail: string;
};

export type HTTPValidationError = {
    detail?: ValidationError[];
};

export type ValidationError = {
    loc: (string | number)[];
    msg: string;
    type: string;
};

export type Vote = {
    id: number;
    name: string;
    status: VoteStatus;
    owner_id: string;
    options: VoteOption[];
};

export type VoteOption = {
    id: number;
    name: string;
};
