/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PollsPollIdImport } from './routes/polls/$pollId'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as PollsPollIdIndexImport } from './routes/polls/$pollId/index'
import { Route as PollsPollIdVoteImport } from './routes/polls/$pollId/vote'
import { Route as PollsPollIdResultsImport } from './routes/polls/$pollId/results'
import { Route as PollsPollIdManageImport } from './routes/polls/$pollId/manage'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PollsPollIdRoute = PollsPollIdImport.update({
  id: '/polls/$pollId',
  path: '/polls/$pollId',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const PollsPollIdIndexRoute = PollsPollIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PollsPollIdRoute,
} as any)

const PollsPollIdVoteRoute = PollsPollIdVoteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => PollsPollIdRoute,
} as any)

const PollsPollIdResultsRoute = PollsPollIdResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => PollsPollIdRoute,
} as any)

const PollsPollIdManageRoute = PollsPollIdManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => PollsPollIdRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/polls/$pollId': {
      id: '/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof PollsPollIdImport
      parentRoute: typeof rootRoute
    }
    '/polls/$pollId/manage': {
      id: '/polls/$pollId/manage'
      path: '/manage'
      fullPath: '/polls/$pollId/manage'
      preLoaderRoute: typeof PollsPollIdManageImport
      parentRoute: typeof PollsPollIdImport
    }
    '/polls/$pollId/results': {
      id: '/polls/$pollId/results'
      path: '/results'
      fullPath: '/polls/$pollId/results'
      preLoaderRoute: typeof PollsPollIdResultsImport
      parentRoute: typeof PollsPollIdImport
    }
    '/polls/$pollId/vote': {
      id: '/polls/$pollId/vote'
      path: '/vote'
      fullPath: '/polls/$pollId/vote'
      preLoaderRoute: typeof PollsPollIdVoteImport
      parentRoute: typeof PollsPollIdImport
    }
    '/polls/$pollId/': {
      id: '/polls/$pollId/'
      path: '/'
      fullPath: '/polls/$pollId/'
      preLoaderRoute: typeof PollsPollIdIndexImport
      parentRoute: typeof PollsPollIdImport
    }
  }
}

// Create and export the route tree

interface PollsPollIdRouteChildren {
  PollsPollIdManageRoute: typeof PollsPollIdManageRoute
  PollsPollIdResultsRoute: typeof PollsPollIdResultsRoute
  PollsPollIdVoteRoute: typeof PollsPollIdVoteRoute
  PollsPollIdIndexRoute: typeof PollsPollIdIndexRoute
}

const PollsPollIdRouteChildren: PollsPollIdRouteChildren = {
  PollsPollIdManageRoute: PollsPollIdManageRoute,
  PollsPollIdResultsRoute: PollsPollIdResultsRoute,
  PollsPollIdVoteRoute: PollsPollIdVoteRoute,
  PollsPollIdIndexRoute: PollsPollIdIndexRoute,
}

const PollsPollIdRouteWithChildren = PollsPollIdRoute._addFileChildren(
  PollsPollIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/polls/$pollId': typeof PollsPollIdRouteWithChildren
  '/polls/$pollId/manage': typeof PollsPollIdManageRoute
  '/polls/$pollId/results': typeof PollsPollIdResultsRoute
  '/polls/$pollId/vote': typeof PollsPollIdVoteRoute
  '/polls/$pollId/': typeof PollsPollIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/polls/$pollId/manage': typeof PollsPollIdManageRoute
  '/polls/$pollId/results': typeof PollsPollIdResultsRoute
  '/polls/$pollId/vote': typeof PollsPollIdVoteRoute
  '/polls/$pollId': typeof PollsPollIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/polls/$pollId': typeof PollsPollIdRouteWithChildren
  '/polls/$pollId/manage': typeof PollsPollIdManageRoute
  '/polls/$pollId/results': typeof PollsPollIdResultsRoute
  '/polls/$pollId/vote': typeof PollsPollIdVoteRoute
  '/polls/$pollId/': typeof PollsPollIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/polls/$pollId'
    | '/polls/$pollId/manage'
    | '/polls/$pollId/results'
    | '/polls/$pollId/vote'
    | '/polls/$pollId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/polls/$pollId/manage'
    | '/polls/$pollId/results'
    | '/polls/$pollId/vote'
    | '/polls/$pollId'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/polls/$pollId'
    | '/polls/$pollId/manage'
    | '/polls/$pollId/results'
    | '/polls/$pollId/vote'
    | '/polls/$pollId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  PollsPollIdRoute: typeof PollsPollIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  PollsPollIdRoute: PollsPollIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/polls/$pollId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/polls/$pollId": {
      "filePath": "polls/$pollId.tsx",
      "children": [
        "/polls/$pollId/manage",
        "/polls/$pollId/results",
        "/polls/$pollId/vote",
        "/polls/$pollId/"
      ]
    },
    "/polls/$pollId/manage": {
      "filePath": "polls/$pollId/manage.tsx",
      "parent": "/polls/$pollId"
    },
    "/polls/$pollId/results": {
      "filePath": "polls/$pollId/results.tsx",
      "parent": "/polls/$pollId"
    },
    "/polls/$pollId/vote": {
      "filePath": "polls/$pollId/vote.tsx",
      "parent": "/polls/$pollId"
    },
    "/polls/$pollId/": {
      "filePath": "polls/$pollId/index.tsx",
      "parent": "/polls/$pollId"
    }
  }
}
ROUTE_MANIFEST_END */
